services:
  flask-app:
    build: .
    container_name: flask-app
    command: flask run --host=0.0.0.0 --port=5001
    ports:
      - "5001:5001"
    environment:
      POSTGRES_DB: lhacksportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/lhacksportal
      CONNECTION_STRING: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/lhacksportal
      
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: lhacksportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
